version: '3.3'
services:
    #baza
    mongo:
        image: 'mongo:latest'
        container_name: 'mongo'
        ports:
            - '27100:27100'
        volumes:
            - type: bind
              source: ./data
              target: /data/db
    #back
    lsbackend:
        container_name: 'lsbackend'
        build: './LetiSleti/LSbackend'
        ports:
            - '8080:8080'
        volumes:
            - './LetiSleti/LSbackend:/app'
        depends_on:
            - 'mongo'
    #front
    lsfrontend:
        container_name: 'lsfrontend'
        build: './LetiSleti/LSfrontend'
        ports:
            - '4200:4200'
        volumes:
            - './LetiSleti/LSfrontend:/usr/local/app'
        depends_on:
            - 'lsbackend'