version: "3.3"
services:
  user_service:
    image: user_service
    container_name: user_service
    build:
      context: .
      dockerfile: ./Skitnica/backend/user_service/Dockerfile
    restart: on-failure
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      USER_SERVICE_PORT: ${USER_SERVICE_PORT}
    depends_on:
      - db_host
    networks:
      - network
  accomodation_service:
    image: accomodation_service
    container_name: accomodation_service
    build:
      context: .
      dockerfile: ./Skitnica/backend/accomodation_service/Dockerfile
    restart: on-failure
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      ACCOMODATION_SERVICE_PORT: ${ACCOMODATION_SERVICE_PORT}
    depends_on:
      - db_host
    networks:
      - network
  accomodation_rating_service:
    image: accomodation_rating_service
    container_name: accomodation_rating_service
    build:
      context: .
      dockerfile: ./Skitnica/backend/accomodation_rating_service/Dockerfile
    restart: on-failure
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      ACCOMODATION_SERVICE_PORT: ${ACCOMODATION_RATING_SERVICE_PORT}
    depends_on:
      - db_host
    networks:
      - network
  appointment_service:
    image: appointment_service
    container_name: appointment_service
    build:
      context: .
      dockerfile: ./Skitnica/backend/appointment_service/Dockerfile
    restart: on-failure
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      APPOINTMENT_SERVICE_PORT: ${APPOINTMENT_SERVICE_PORT}
    depends_on:
      - db_host
    networks:
      - network
  reservation_service:
    image: reservation_service
    container_name: reservation_service
    build:
      context: .
      dockerfile: ./Skitnica/backend/reservation_service/Dockerfile
    restart: on-failure
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      RESERVATION_SERVICE_PORT: ${RESERVATION_SERVICE_PORT}
    depends_on:
      - db_host
    networks:
      - network
  
  hostmark_service:
    image: hostmark_service
    container_name: hostmark_service
    build:
      context: .
      dockerfile: ./Skitnica/backend/hostmark_service/Dockerfile
    restart: on-failure
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      HOSTMARK_SERVICE_PORT: ${HOSTMARK_SERVICE_PORT}
    depends_on:
      - db_host
    networks:
      - network
      
  api_gateway:
    image: api_gateway
    container_name: api_gateway
    build:
      context: .
      dockerfile: ./Skitnica/backend/api_gateway/Dockerfile
    restart: on-failure
    ports:
      - ${GATEWAY_PORT}:${GATEWAY_PORT}
    environment:
      GATEWAY_PORT: ${GATEWAY_PORT}
      USER_SERVICE_HOST: ${USER_SERVICE_HOST}
      USER_SERVICE_PORT: ${USER_SERVICE_PORT}
      ACCOMODATION_SERVICE_HOST: ${ACCOMODATION_SERVICE_HOST}
      ACCOMODATION_SERVICE_PORT: ${ACCOMODATION_SERVICE_PORT}
      APPOINTMENT_SERVICE_HOST: ${APPOINTMENT_SERVICE_HOST}
      APPOINTMENT_SERVICE_PORT: ${APPOINTMENT_SERVICE_PORT}
      RESERVATION_SERVICE_HOST: ${RESERVATION_SERVICE_HOST}
      RESERVATION_SERVICE_PORT: ${RESERVATION_SERVICE_PORT}
      HOSTMARK_SERVICE_HOST: ${HOSTMARK_SERVICE_HOST}
      HOSTMARK_SERVICE_PORT: ${HOSTMARK_SERVICE_PORT}

    networks:
      - network

  db_host:
    image: mongo
    container_name: db_host
    restart: on-failure
    networks:
      - network
    ports:
      - ${DB_PORT}:${DB_PORT}

  # accomodation_db:
  #   image: mongo
  #   container_name: accomodation_db
  #   restart: on-failure
  #   networks:
  #     - network
  #   ports:
  #     - 27018:${ACCOMODATION_DB_PORT} # test

  # appointment_db:
  #   image: mongo
  #   container_name: appointment_db
  #   restart: on-failure
  #   networks:
  #     - network

  # reservation_db:
  #   image: mongo
  #   container_name: reservation_db
  #   restart: on-failure
  #   networks:
  #     - network
  #   ports:
  #     - ${RESERVATION_DB_PORT}:${RESERVATION_DB_PORT}
networks:
  network:
    driver: bridge

  # #baza
  # mongo:
  #   image: "mongo:latest"
  #   container_name: "mongo"
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - type: bind
  #       source: ./data
  #       target: /data/db
  # #back
  # lsbackend:
  #   container_name: "lsbackend"
  #   build: "./LetiSleti/LSbackend"
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - "./LetiSleti/LSbackend:/app"
  #   depends_on:
  #     - "mongo"
  # #front
  # lsfrontend:
  #   container_name: "lsfrontend"
  #   build: "./LetiSleti/LSfrontend"
  #   ports:
  #     - "4200:4200"
  #   volumes:
  #     - "./LetiSleti/LSfrontend:/usr/local/app"
  #   depends_on:
  #     - "lsbackend"
